### ISSUE TITLE
Disable automountServiceAccountToken by default

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/gatekeeper-library#47]
We should set `automountServiceAccountToken` to `false` by default if not configured. That means that if someone actually sets it to `true`, it should be allowed.

This should only be done in tenant namespaces.

**Comment by bittrance** [comment]
It’s a good thing, but how do we roll it out to existing tenant mamespaces?

I think this implies that we need to write the documentation where this will be one item (in bold, prolly).
